// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Runtime.Serialization;

namespace TestApp.fire
{
    [DataContract]
    public class Cost
    {
        [DataMember]
        public int type { get; set; }
        [DataMember]
        public int value { get; set; }
    }
    [DataContract]
    public class Upgrade
    {
        /// <summary>
        /// 是否可以升级
        /// </summary>
        [DataMember]
        public bool upgradeEnable { get; set; }
        /// <summary>
        /// 毫秒数
        /// </summary>
        [DataMember]
        public int time { get; set; }
        /// <summary>
        /// type=1,银两;type=2,木材
        /// </summary>
        [DataMember]
        public IList<Cost> cost { get; set; }
    }
    [DataContract]
    public class Building
    {
        [DataMember]
        public int harvest { get; set; }
        [DataMember]
        public int type { get; set; }
        [DataMember]
        public int id { get; set; }
        [DataMember]
        public string name { get; set; }
        [DataMember]
        public string intro { get; set; }
        [DataMember]
        public bool canChanged { get; set; }
        [DataMember]
        public bool isChanged { get; set; }
        [DataMember]
        public int outputType { get; set; }
        [DataMember]
        public int output { get; set; }
        [DataMember]
        public int speedUpNum { get; set; }
        [DataMember]
        public int totalUpNum { get; set; }
        [DataMember]
        public int lv { get; set; }
        [DataMember]
        public int pos { get; set; }
        [DataMember]
        public int resType { get; set; }
        [DataMember]
        public bool isNew { get; set; }
        [DataMember]
        public bool hasEvent { get; set; }
        [DataMember]
        public Upgrade upgrade { get; set; }
    }
    [DataContract]
    public class TotalOutput
    {
        [DataMember]
        public int type { get; set; }
        [DataMember]
        public int output { get; set; }
    }
    [DataContract]
    public class AutoUpbuilding
    {
        [DataMember]
        public int times { get; set; }
        [DataMember]
        public int areaId { get; set; }
        [DataMember]
        public int state { get; set; }
    }
    [DataContract]
    public class BuildingWork
    {
        [DataMember]
        public int workId { get; set; }
        [DataMember]
        public int state { get; set; }
    }
    [DataContract]
    public class webBuildingData
    {
        [DataMember]
        public IList<Building> buildings { get; set; }
        [DataMember]
        public bool tip { get; set; }
        [DataMember]
        public IList<TotalOutput> totalOutput { get; set; }
        [DataMember]
        public AutoUpbuilding autoUpbuilding { get; set; }
        [DataMember]
        public int additionMode { get; set; }
        [DataMember]
        public int additionRate { get; set; }
        [DataMember]
        public int additionCd { get; set; }
        [DataMember]
        public IList<BuildingWork> buildingWorks { get; set; }
        [DataMember]
        public int freeConsNum { get; set; }
        [DataMember]
        public int kidnapper { get; set; }
        [DataMember]
        public int hasBandit { get; set; }
    }
    //[DataContract]
    //public class Action
    //{
    //    [DataMember]
    //    public int state { get; set; }
    //    [DataMember]
    //    public Data data { get; set; }
    //}
    //[DataContract]
    //public class webBuildingAction
    //{
    //    [DataMember]
    //    public Action action { get; set; }
    //}

}
