// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Runtime.Serialization;

namespace TestApp.fire
{
     [DataContract]
    public class Task
    {

        [DataMember]
         public int type { get; set; }

        [DataMember]
        public int state { get; set; }

        [DataMember]
        public int taskId { get; set; }

        [DataMember]
        public int group { get; set; }

        [DataMember]
        public int index { get; set; }

        [DataMember]
        public string taskName { get; set; }

        [DataMember]
        public string introShort { get; set; }

        [DataMember]
        public string introLong { get; set; }

        [DataMember]
        public string processStr { get; set; }

        [DataMember]
        public bool requestCompleted { get; set; }

        [DataMember]
        public string markTrace { get; set; }

        [DataMember]
        public string iosMarktrace { get; set; }

        [DataMember]
        public string newTrace { get; set; }

        [DataMember]
        public int areaId { get; set; }

        [DataMember]
        public string pic { get; set; }

        [DataMember]
        public string plot { get; set; }
    }
     [DataContract]
    public class webCurTask
    {

        [DataMember]
        public IList<Task> tasks { get; set; }
    }

}
