// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.Serialization;

namespace TestApp.fire
{

  [DataContract]
    public class God
    {

        [DataMember]
        public int GodId { get; set; }

        [DataMember]
        public int ResourceType { get; set; }

        [DataMember]
        public int Gold { get; set; }
    }

  [DataContract]
    public class webIncense_getIncenseInfo
    {

        [DataMember]
        public IList<God> Gods { get; set; }

        [DataMember]
        public int CurrentIncenseNum { get; set; }

        [DataMember]
        public int IncenseGold { get; set; }

        [DataMember]
        public bool BigIncense { get; set; }

        [DataMember]
        public int FreeBigIncenseNum { get; set; }

        [DataMember]
        public int IncenseMax { get; set; }
    }

}
