// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Runtime.Serialization;


namespace TestApp.fire
{

    public class NyRedPaperExtraRewardInfo
    {
        [DataMember]
        public bool have { get; set; }
        [DataMember]
        public bool received { get; set; }
    }

    //public class TotalOutput
    //{
    //    [DataMember]
    //    public int type { get; set; }
    //    [DataMember]
    //    public int output { get; set; }
    //}

    public class OfficerOutput
    {
        /// <summary>
        /// =1:银两;=2:木材;=3:粮食;=4:铁矿;=5:兵营出兵速度
        /// </summary>
        [DataMember]
        public int type { get; set; }
        [DataMember]
        public int value { get; set; }
    }

    public class Area
    {
        [DataMember]
        public int id { get; set; }
        [DataMember]
        public int pbwNum { get; set; }
        [DataMember]
        public bool isOpen { get; set; }
        [DataMember]
        public bool hasEvent { get; set; }
        [DataMember]
        public int additionMode { get; set; }
        [DataMember]
        public int additionRate { get; set; }
        [DataMember]
        public int additionCd { get; set; }
        [DataMember]
        public IList<TotalOutput> totalOutput { get; set; }
        [DataMember]
        public int? addition { get; set; }
        [DataMember]
        public IList<OfficerOutput> officerOutput { get; set; }
    }

    public class webMainCityData
    {
        [DataMember]
        public NyRedPaperExtraRewardInfo nyRedPaperExtraRewardInfo { get; set; }
        [DataMember]
        public IList<Area> areas { get; set; }
        [DataMember]
        public int troopLv { get; set; }
    }

}
