// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.Serialization;

namespace TestApp.fire
{

  [DataContract]
    public class OutputInfo
    {// 各种材料的产量
        /// <summary>
        /// =1:银两;=2:木材;=3:粮食;=4:矿产
        /// </summary>
        [DataMember]
        public int BuildingType { get; set; }

      /// <summary>
      /// 未知
      /// </summary>
        [DataMember]
        public int Output { get; set; }

        /// <summary>
        /// 当前总量
        /// </summary>
        [DataMember]
        public int RealValue { get; set; }
    }

  [DataContract]
    public class Output
    {

        [DataMember]
        public IList<OutputInfo> OutputInfo { get; set; }

        [DataMember]
        public bool IsChangeDisplaye { get; set; }
    }

  [DataContract]
    public class webOutput
    {

        [DataMember]
        public Output Output { get; set; }
    }

}
