// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.Serialization;

namespace TestApp.fire
{
    /*
  [DataContract]
    public class Cost
    {

        [DataMember]
        public int Type { get; set; }

        [DataMember]
        public int Value { get; set; }
    }

  [DataContract]
    public class Upgrade
    {

        [DataMember]
        public bool UpgradeEnable { get; set; }

        [DataMember]
        public int Time { get; set; }

        [DataMember]
        public IList<Cost> Cost { get; set; }
    }

  [DataContract]
    public class Building
    {

        [DataMember]
        public int Harvest { get; set; }

        [DataMember]
        public int Type { get; set; }

        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public string Name { get; set; }

        [DataMember]
        public bool CanChanged { get; set; }

        [DataMember]
        public bool IsChanged { get; set; }

        [DataMember]
        public int OutputType { get; set; }

        [DataMember]
        public int Output { get; set; }

        [DataMember]
        public int SpeedUpNum { get; set; }

        [DataMember]
        public int TotalUpNum { get; set; }

        [DataMember]
        public int Lv { get; set; }

        [DataMember]
        public int Pos { get; set; }

        [DataMember]
        public int ResType { get; set; }

        [DataMember]
        public bool IsNew { get; set; }

        [DataMember]
        public bool HasEvent { get; set; }

        [DataMember]
        public Upgrade Upgrade { get; set; }
    }

  [DataContract]
    public class TotalOutput
    {

        [DataMember]
        public int Type { get; set; }

        [DataMember]
        public int Output { get; set; }
    }

  [DataContract]
    public class AutoUpbuilding
    {

        [DataMember]
        public int Times { get; set; }

        [DataMember]
        public int AreaId { get; set; }

        [DataMember]
        public int State { get; set; }
    }

  [DataContract]
    public class BuildingWork
    {

        [DataMember]
        public int WorkId { get; set; }

        [DataMember]
        public int State { get; set; }
    }*/
  /// <summary>
  /// 城外的林场信息
  /// </summary>
  [DataContract]
    public class webWoodInfo
    {

        [DataMember]
        public IList<Building> Buildings { get; set; }

        [DataMember]
        public bool Tip { get; set; }

        [DataMember]
        public IList<TotalOutput> TotalOutput { get; set; }

        [DataMember]
        public AutoUpbuilding AutoUpbuilding { get; set; }

        [DataMember]
        public int AdditionMode { get; set; }

        [DataMember]
        public int AdditionRate { get; set; }

        [DataMember]
        public int AdditionCd { get; set; }

        [DataMember]
        public IList<BuildingWork> BuildingWorks { get; set; }

        [DataMember]
        public int FreeConsNum { get; set; }

        [DataMember]
        public int HasBandit { get; set; }
    }

}
